apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server-normal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-server-normal
  template:
    metadata:
      labels:
        app: http-server-normal
    spec:
      containers:
        - name: demo
          image: frederikpietzko/http-server-normal:latest
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: http-server-normal
spec:
  selector:
    app: http-server-normal
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
